spring:
  application:
    name: api-command

  docker:
    compose:
      enabled: false

#  kafka:
#    bootstrap-servers: ""
#
#  datasource:
#    driver-class-name :

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

operation-manager:
  webmvc:
    mdc-service-aspect:
      enabled: true
    micrometer:
      enabled: true