spring:
  application:
    name: api-command

adapter:

  security:
    verifier:
      policy:
        key-alias: access-token-sig
        expected-issuers:
          - Whiteprint
      entry-points:
        - path: /test
          method: GET
          decision: PERMIT
        - path: /test
          method: POST
          decision: PERMIT
      kms:
        datasource:
          host: sinandle.iptime.org
          port: 8200
          password: root
          transit-path: transit
        cache:
          expires-after-write-minutes: 60
          maximum-size: 1000
      cache:
        datasource:
          host: sinandle.iptime.org
          port: 6379
          password: ~
          database: 0
        pooling:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait-millis: -1
        timeout:
          command-timeout-millis: 2000
          shutdown-timeout-millis: 100

  event:
    publisher:
      infrastructure-implementation: kafka
      kafka:
        datasource:
          host: sinandle.iptime.org
          port: 9092
        topic-policy:
          auto-create: true
          prefix: test
          topic: user
          version: v1
          separator: .
          default-partitions: 3
          default-replication-factor: 1
          retention-millis: 604800000
          cleanup-policy: delete
        producer:
          acks: all
          batch-size: 16384
          linger-millis: 5
          compression-type: lz4
          retries: 2147483647
        publish:
          retry:
            max-attempts: 3
            backoff-interval: 2000

    outbox:
      infrastructure-implementation: jpa

    subscriber:
      infrastructure-implementation: kafka
      kafka:
        datasource:
          host: sinandle.iptime.org
          port: 9092
        consumer:
          group-id: platform-group
          auto-offset-reset: earliest
          concurrency: 3
          enable-auto-commit: false
          isolation-level: read_committed
        error-handling:
          retry:
            max-attempts: 3
            backoff-interval: 2000
          dead-letter:
            enabled: true
            topic-suffix: .DLT
            producer:
              acks: all
              batch-size: 16384
              linger-millis: 5
              compression-type: lz4
              retries: 2147483647

  persistence:
    infrastructure-implementation: jpa
    jpa:
      datasource:
        database: postgresql
        driver-class-name: ~ #Automatically Configured. Skip Recommended
        host: sinandle.iptime.org
        port: 5432
        database-name: mydatabase
        #parameters:
        username: postgres
        password: postgres
      hikari:
        maximum-pool-size: 10
        minimum-idle: 10
        connection-timeout-millis: 30000
        idle-timeout-millis: 600000
        max-lifetime-millis: 1800000
        auto-commit: false
        pool-name: myhikaripool
      hibernate:
        fetch-size: 1000
        batch-size: 100
        provider-disables-autocommit: true
        generate-statistics: false
        batch-versioned-data: true
        order-inserts: true
        order-updates: true
        format-sql: true
        highlight-sql: true
        ddl-auto: none
        default-batch-fetch-size: 100
      options:
        packages-to-scan:
          - "org.whiteprint.service.user"
        show-sql: false
        generate-ddl: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    endpoint:
      prometheus:
        enabled: true
  observations:
    key-values:
      application: ${spring.application.name}


operation-manager:
  webmvc:
    mdc-service-aspect:
      enabled: true
    micrometer:
      enabled: true
    logging:
      enabled: true
      pretty: true
      json: true
      success-level: INFO
      failure-level: ERROR