spring:
  application:
    name: api-command

  docker:
    compose:
      enabled: false

#  kafka:
#    bootstrap-servers: ""
#
#  datasource:
#    driver-class-name :

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    endpoint:
      prometheus:
        enabled: true
  observations:
    key-values:
      application: ${spring.application.name}


operation-manager:
  webmvc:
    mdc-service-aspect:
      enabled: true
    micrometer:
      enabled: true
    logging:
      enabled: true
      pretty: true
      json: true
      success-level: INFO
      failure-level: ERROR